PATIENT_PROFILE_FILE_NAME: output/registrations.csv
ENCOUNTER_PROFILE_FILE_NAME: output/encounters.csv
REGISTRATION_INDEX_START_POINT: 600
PATIENT_REGISTRATION_START_DAY: "2000-02-11"
BASEURL : https://localhost
UNAME: superman
PASSWORD: Admin123
LOCATION: CURE Ethiopia

REG_INITIAL: ET
PATIENT_COUNT: 100
S_CREATE_ENCOUNTER: N
ENCOUNTER_COUNT: 2
S_UPLOAD_CSV: y
