patientProfileFileName: output/registrations.csv
contactProfileFileName: output/encounters.csv
registrationIndexStartPoint: 1011
patientRegistrationStartDay: "2014-02-11"
baseUrl : http://localhost:8080
regInitial: PERF
patientProfileCount: 50
sCreateContact: y
contactCount: 50
