PATIENT_PROFILE_FILE_NAME: output/registrations.csv
ENCOUNTER_PROFILE_FILE_NAME: output/encounters.csv
MEDICATION_ORDER_PROFILE_FILE_NAME: output/medicationOrder.csv
REGISTRATION_INDEX_START_POINT: 1011
PATIENT_REGISTRATION_START_DAY: "2014-02-11"
BASEURL :
USERNAME:
PASSWORD:
LOCATION: General Ward

REG_INITIAL: GAN
PATIENT_COUNT: 2000
S_CREATE_ENCOUNTER: y
ENCOUNTER_COUNT: 2000
SCENARIO: PRENATAL_SUPPLEMENTS
S_UPLOAD_CSV: y
S_CREATE_DIAGNOSIS_CONCEPTS: y
S_UPLOAD_MEDICATIONS: y
CONCEPT_SOURCE_SNOMED_UUID : cb523690-9012-4e72-b8bf-4253e1b1a687
CONCEPT_MAPPING_SAME_AS_UUID : 35543629-7d8c-11e1-909d-c80aa9edcf4e
CONCEPT_CLASS_DIAGNOSIS_UUID : 8d4918b0-c2cc-11de-8d13-0010c6dffd0f
CONCEPT_DATATYPE_NA_UUID: 8d4a4c94-c2cc-11de-8d13-0010c6dffd0f

SNOWSTORM_URL :
