patientProfileFileName: output/registrations.csv
contactProfileFileName: output/encounters.csv
registrationIndexStartPoint: 1011
patientRegistrationStartDay: "2014-02-11"
baseUrl : https://demo-v94.mybahmni.org
user: superman
password: Admin123
location: Registration Desk

regInitial: PERF
PATIENT_COUNT: 10
sCreateContact: y
ENCOUNTER_COUNT: 10
sUploadCsv: y
