PATIENT_PROFILE_FILE_NAME: output/registrations.csv
ENCOUNTER_PROFILE_FILE_NAME: output/encounters.csv
REGISTRATION_INDEX_START_POINT: 1011
PATIENT_REGISTRATION_START_DAY: "2014-02-11"
BASEURL : https://dev.snomed.mybahmni.in
USERNAME: superman
PASSWORD: Admin123
LOCATION: General Ward

REG_INITIAL: GAN
PATIENT_COUNT: 10
S_CREATE_ENCOUNTER: y
ENCOUNTER_COUNT: 10
SCENARIO: PRENATAL_SUPPLEMENTS
S_UPLOAD_CSV: y

SNOWSTORM_URL : https://snomstorm.snomed.mybahmni.in/fhir
